version: "3"
services:
  catalogservice:
    build: ./Catalog
    container_name: catalogservice
    ports:
      - "8000:8000"
    networks:
      - my_network

  orderservice:
    build: ./Order
    container_name: orderservice
    ports:
      - "8002:8002"
    networks:
      - my_network

  feservice:
    build: ./FE
    container_name: feservice
    ports:
      - "8001:8001"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
